# Generated by Django 4.2.3 on 2023-08-02 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorevent",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sensorevent",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_events",
                to="main.sensor",
            ),
        ),
    ]
