# Generated by Django 4.2.3 on 2023-08-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_sensorevent_count_alter_sensorevent_sensor"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="fri_avg_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sensor",
            name="mon_avg_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sensor",
            name="sat_avg_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sensor",
            name="sun_avg_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sensor",
            name="thu_avg_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sensor",
            name="tue_avg_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sensor",
            name="wed_avg_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
