# Generated by Django 4.2.3 on 2023-08-02 03:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_sensor_fri_avg_count_sensor_mon_avg_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensor",
            old_name="name",
            new_name="sensor_name",
        ),
    ]
